### ISSUE TITLE
What do you use to view .pak files

### ISSUE THREAD

**Issue by vidicunt** [dippyshere/fortnite-aes-archive#12]
Gildor does not support Unreal Engine 5

Getting a "Missing LoaderGlobalNameHashes chunk" error

**Comment by dippyshere** [comment]
https://github.com/4sval/FModel

**Comment by vidicunt** [comment]
FModel doesn't seem to work with Fortnite's UE5, as in .uassets can't be properly extracted and the dev refuses to give support despite multiple people opening issues.

Do you know of an alternative? or am I missing something?

**Comment by dippyshere** [comment]
Use the latest beta version and read the big red warning on start-up (genxgames.gg)
