### ISSUE TITLE
5.41 Missing AES Key

### ISSUE THREAD

**Issue by DevlinCPerks** [dippyshere/fortnite-aes-archive#16]
there isnt a aes key for version 5.41. do you think you could add that?

**Comment by dippyshere** [comment]
If I / somebody knew the key, it would be here already 🙃

If you've got the build/ PAKs, you can either reverse engineer the key yourself from the game upon startup, OR you can try some of the surrounding keys (known keys above /below).

Report back with your findings if you try any of these and I'll help you create a pull request if you find a working key :D

**Comment by dippyshere** [comment]
Added in 97e43185df48a029aefa04c9c57888cad53c66e5
