### ISSUE TITLE
These keys utility

### ISSUE THREAD

**Issue by RagBom7** [dippyshere/fortnite-aes-archive#18]
What are these keys for? Is it to download Fortnite builds or something like that?

**Comment by dippyshere** [comment]
Hi! These keys are used to encrypt / decrypt the contents of the game's PAK files (where all content data like textures, models, sounds, etc are stored). These keys can be used by us to explore and extract the data content for a specific version. The game does not need us to provide the main key to work by itself, as this is contained within the game executable to function properly.

The dynamic keys are keys provided by the server over the API to allow the game to decrypt content that was specifically put into a separate PAK file not encrypted with the same key as other PAKs. These dynamic keys must be provided by the server (be it official or private) in order for the specific content to be accessed in a specific build (e.g. live events, certain cosmetics, etc).

These keys change frequently with every game update, and are archived here for the sake of preservation, to allow this content to be more easily accessed and playable in the future.

**Comment by RagBom7** [comment]
Ok, thank you so much for the information :)
