### ISSUE TITLE
Memory Allocation Error

### ISSUE THREAD

**Issue by xHybred** [dippyshere/fortnite-aes-archive#19]
So in QuickBMS I keep getting _"memory allocation problem. Acess is denied."_ when inputting the AES key for Pakchunk0

I'm only trying to access DefaultEngine.ini DefaultScalability BaseEngine.ini BaseScalability & WindowsEngine.ini

None of these are large files, I'm not trying to asset rip or debug the game for cheating, I'm just an unreal engine 5 developer trying to see how Epic Games solved some problems I'm facing by looking at their cvars.

If anyone could either give these too me or help me troubleshoot my problem so I can do it myself it would be much appreciated

**Comment by dippyshere** [comment]
Hello! I'm not too familiar with how QuickBMS handles PAK files; it's possible that their implementation doesn't currently support the latest features and formats that Fortnite uses.

For your use case, I'd recommend you check out FModel (and use the QA branch builds) if it's possible for you to run it. That tool is already setup out of the box to get the latest AES keys and mappings for Fortnite when you select it, and works great for tons of UE4/5 games.

If you're still having trouble I can send those files for you.

**Comment by xHybred** [comment]
Hey thanks for the quick reply.

Yes I'm still having trouble because when checking with FModel certain pak files are greyed out and I'm unable to load them (for whatever reason. AES related? My build of the app?)

**Comment by dippyshere** [comment]
If these are PAK chunks in the rage ~1000 - ~1xxx then this is expected. These PAKs are using dynamic encryption keys that differ from the other PAK chunks. You can try going to Directory -> AES -> Refresh to force update the keys used. As long as you're able to load PAK chunk 0, then you should be able to find the configs you need.

**Comment by xHybred** [comment]
Pakchunk0-WindowsClient.pak is the Pak I'm attempting to open actually as I believe that's where the config engine files are which I'm interested in and am having issues with it since it's greyed out.

After doing your steps it's still greyed out for me after using using the latest FModel QA Testing build and doing the AES refresh.

I do appreciate you attempting to help me btw, and I hope this can be resolved

**Comment by dippyshere** [comment]
I'm not sure what else could be causing this issue; the only other things I can think of (mappings and engine version) would at least allow it to attempt to load. I believe these are the files you are looking for (plus a few extras):
[FortniteGameConfigs.zip](https://github.com/dippyshere/fortnite-aes-archive/files/14075437/FortniteGameConfigs.zip)
Hopefully you find the CVars that fix your issue :D

**Comment by xHybred** [comment]
Yeah that's it! thank you very much.

And I'm just seeing how Fortnite compiles its shaders and some other things, their documentation of it isn't the best and Fortnite does an okayish job. I mean afterall they did make Unreal Engine so I'd hope so.

This will help with my video game (hopefully) thanks for your assistance
